apiVersion: v1
kind: Pod
metadata:
  name: debug-power
  labels:
    app: debugbox
    variant: power
spec:
  containers:
  - name: debugbox
    image: ghcr.io/ibtisam-iq/debugbox:power
    command: ["/bin/bash"]
    securityContext:
      # Don't use privileged unless absolutely necessary
      privileged: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    tty: true
    stdin: true
  restartPolicy: Never
